# Hi, I am going to create config file for email notification
jobs:
  send_email_notification:
    docker:
      - image: circleci/python:3.7

    steps:
      - run:
          name: Send email notification
          command: |
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Circle-Token: b681674a8e9ab815cd3fd25aa154c3b8dbe0adde" \
              -d '{
                "to": "altamashfaridi2023@gmail.com",
                "subject": "Custom email notification",
                "body": "This is a custom email notification message."
              }' \
              https://circleci.com/api/v2/notify/email

